name: Refresh metadata
on:
  push:
    branches:
      main
  schedule:
    - cron: '0 */3 * * *'
jobs:
  refresh_metadata:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v2
      name: Cache dependencies
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fetch metadata
      run: |
        python app.py
    - name: Deploy 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.TOKEN }}
        user_name: Code for IATI bot
        user_email: 57559326+codeforIATIbot@users.noreply.github.com
        publish_dir: ./out
        enable_jekyll: true
        force_orphan: true
        allow_empty_commit: true
